#!/bin/bash

#Script to be run by cron to do the hourly scraping

echo "start" $(date) >>/home/leheli/scrape/log
/usr/bin/java -verbose:gc -Xmx300m -jar /home/leheli/scrape/hello-assembly-1.0.jar &>>/home/leheli/scrape/log

echo "end" $(date) >>/home/leheli/scrape/log


