/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'leheli' at '7/19/15 1:46 PM' with Gradle 2.5
 *
 * @author leheli, @date 7/19/15 1:46 PM
 */
package com.scrape.config

import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import javax.sql.DataSource
import org.apache.commons.dbcp.BasicDataSource
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import javax.annotation.Resource
import scala.beans.BeanProperty
import com.scrape.HelloWorld

@Configuration
class DBConfig 
{  
  @Resource
  @BeanProperty
  var dataSource:DataSource=_
  
  @Bean 
   def helloWorld():HelloWorld={
       new HelloWorld("maci");
   }
   
   @Bean
   def getDS():DataSource={
     val ds:BasicDataSource =new BasicDataSource
     ds.setDriverClassName("org.sqlite.JDBC")
     ds.setUrl("jdbc:sqlite:src/main/resources/reddit.db")
     ds.setInitialSize(1)
     ds.setMaxActive(1)
     ds.setMaxIdle(1)
     ds.setPoolPreparedStatements(true)
     ds
   } 
   
   @Bean
   def namedJdbc():NamedParameterJdbcTemplate={
     val np=new NamedParameterJdbcTemplate(dataSource)
     np
   }
   
  def someLibraryMethod(): Boolean = true
}
